// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuiShRBjyL-TG6CPTYfhJmzfa8sjLwO7o',
    appId: '1:559450667948:web:ad3f06b8818308238d5809',
    messagingSenderId: '559450667948',
    projectId: 'move-mate-app',
    authDomain: 'move-mate-app.firebaseapp.com',
    storageBucket: 'move-mate-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv1-LeISURD5e6C4HOeyOXOLUg14nF-sQ',
    appId: '1:559450667948:android:8bec8d13f62b8a9e8d5809',
    messagingSenderId: '559450667948',
    projectId: 'move-mate-app',
    storageBucket: 'move-mate-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBQONPkvXjhNYrXlOLENAO40aqm7fbAM',
    appId: '1:559450667948:ios:27dc5c9b0b15663c8d5809',
    messagingSenderId: '559450667948',
    projectId: 'move-mate-app',
    storageBucket: 'move-mate-app.appspot.com',
    iosBundleId: 'com.example.moveMate',
  );
}
